/* Request Body Schemas for Documentation */
/* Keys must be unique */

const Definitions = {
  SampleGetResponse: {
    records: [
      {
        transactionId: 1,
        firstName: "Akiza",
        lastName: "Dyan",
        contact: "987654",
        purpose: "visit",
        vehicleOrWalk: "vehicle",
        status: 0,
      },
      {
        transactionId: 2,
        firstName: "akiza",
        lastName: "rojo",
        contact: "123",
        purpose: "123",
        vehicleOrWalk: "vehicle",
        status: 0,
      },
      {
        transactionId: 3,
        firstName: "123",
        lastName: "123",
        contact: "123",
        purpose: "123",
        vehicleOrWalk: "walk-in",
        status: 0,
      },
      {
        transactionId: 4,
        firstName: "123",
        lastName: "123",
        contact: "123",
        purpose: "123",
        vehicleOrWalk: "walk-in",
        status: 0,
      },
      {
        transactionId: 5,
        firstName: "123",
        lastName: "123",
        contact: "123",
        purpose: "123",
        vehicleOrWalk: "walk-in",
        status: 0,
      },
      {
        transactionId: 6,
        firstName: "123",
        lastName: "123",
        contact: "123",
        purpose: "123",
        vehicleOrWalk: "walk-in",
        status: 0,
      },
      {
        transactionId: 7,
        firstName: "123",
        lastName: "123",
        contact: "123",
        purpose: "123",
        vehicleOrWalk: "walk-in",
        status: 0,
      },
      {
        transactionId: 8,
        firstName: "123",
        lastName: "123",
        contact: "123",
        purpose: "123",
        vehicleOrWalk: "walk-in",
        status: 0,
      },
      {
        transactionId: 9,
        firstName: "123",
        lastName: "123",
        contact: "123",
        purpose: "123",
        vehicleOrWalk: "walk-in",
        status: 0,
      },
      {
        transactionId: 10,
        firstName: "123",
        lastName: "123",
        contact: "123",
        purpose: "123",
        vehicleOrWalk: "walk-in",
        status: 0,
      },
      {
        transactionId: 11,
        firstName: "123",
        lastName: "123",
        contact: "123",
        purpose: "123",
        vehicleOrWalk: "walk-in",
        status: 0,
      },
      {
        transactionId: 12,
        firstName: "123",
        lastName: "123",
        contact: "123",
        purpose: "123",
        vehicleOrWalk: "walk-in",
        status: 0,
      },
      {
        transactionId: 13,
        firstName: "123",
        lastName: "123",
        contact: "123",
        purpose: "123",
        vehicleOrWalk: "vehicle",
        status: 0,
      },
      {
        transactionId: 14,
        firstName: "123",
        lastName: "123",
        contact: "123",
        purpose: "123",
        vehicleOrWalk: "walk-in",
        status: 0,
      },
      {
        transactionId: 15,
        firstName: "123",
        lastName: "123",
        contact: "123",
        purpose: "123",
        vehicleOrWalk: "vehicle",
        status: 0,
      },
      {
        transactionId: 16,
        firstName: "123",
        lastName: "123",
        contact: "123",
        purpose: "123",
        vehicleOrWalk: "vehicle",
        status: 1,
      },
      {
        transactionId: 17,
        firstName: "123",
        lastName: "123",
        contact: "123",
        purpose: "123",
        vehicleOrWalk: "vehicle",
        status: 1,
      },
      {
        transactionId: 18,
        firstName: "23",
        lastName: "123",
        contact: "123",
        purpose: "12",
        vehicleOrWalk: "walk-in",
        status: 1,
      },
      {
        transactionId: 19,
        firstName: "23555",
        lastName: "123",
        contact: "123",
        purpose: "12",
        vehicleOrWalk: "walk-in",
        status: 0,
      },
      {
        transactionId: 20,
        firstName: "23555",
        lastName: "123",
        contact: "123",
        purpose: "12",
        vehicleOrWalk: "walk-in",
        status: 0,
      },
      {
        transactionId: 21,
        firstName: "123",
        lastName: "123",
        contact: "123",
        purpose: "123",
        vehicleOrWalk: "vehicle",
        status: 1,
      },
      {
        transactionId: 22,
        firstName: "123",
        lastName: "123",
        contact: "123",
        purpose: "123",
        vehicleOrWalk: "vehicle",
        status: 1,
      },
      {
        transactionId: 23,
        firstName: "123",
        lastName: "123",
        contact: "123",
        purpose: "123",
        vehicleOrWalk: "vehicle",
        status: 1,
      },
    ],
    totalCount: 23,
    page: 1,
  },

  SamplePostRequest: {
    firstName: "Grextor",
    lastName: "Arkiza",
    contact: "678934",
    purpose: "Visit",
    selectedOption: "vehicle",
  },

  SamplePostResponse: {
    message: "Successfully registed a visitor",
  },

  SamplePutRequest: {
    transactionId: 1,
    status: 0,
  },

  SamplePutResponse: {
    message: "Successfully updated a visitor",
  },
  InternalServerError: {
    message: "error",
  },
};
module.exports = Definitions;
